# -*- coding: utf-8 -*-
"""Copy of Capstone_11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HVw2ltL4mLvY2Gju1-sw6mfvjOyCajpL

Topic: Spam Email Classifiers

# 1. Import Necessary Libraries
"""

import numpy as np
import pandas as pd
import re
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score, f1_score
import seaborn as sns
import matplotlib.pyplot as plt

import nltk

!unzip /usr/share/nltk_data/corpora/wordnet.zip -d /usr/share/nltk_data/corpora/

from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

"""## 1.1. Import Dataset from Kaggle"""

df = pd.read_csv('/content/archive (4).zip')

"""# 2. Viewing Properties of Dataset

2.1 Vieing Shape of Dataframe
This shows that they are 2 columns and 5,559 rows in the data set.
"""

df.shape

"""2.2. Dataset information;
This gives a summary of the information contained in the dataset as it concerns the number of entries, rows/columns, datatype, missing values etc
"""

df.info()

"""2.3 ;Dataset Preview - from head or tail:
This displays a range of the set, either from the top or bottome entries.
"""

df.head(20)

df.tail()

"""## 2.4 Describing the dataframe:
This gives the statistical analysis of the dataset where necessary.
"""

df.describe()

df.describe().T

"""# 3. Cleaning Dataset

## 3.1. Checking for Missing Values.
This show if there are missing enteries and the data type, whether it is a string, int, bollian or float.

##
"""

df.isnull().sum()

"""## 3.2. Checking for Duplicate:
This checks if they are duplicate entries in the dataframe.
The output below shows that they are 403 uplicates in the entry and all are of the INT data type.
"""

df.duplicated().sum()

"""## 3.2.1. After Dropping Duplicate.
On dropping 403 duplicated entries from the 5,559 entries, it remaining 5,156 rows arranged in 2 columns.
"""

df.drop_duplicates()

"""# 4. Trainig the Dataset
This generates a Random Forec classifier, using the training data into X train (Training_input_data) and y train (Training_output_data), which will them make prediction on the data.
"""

vectorizer = TfidfVectorizer(stop_words="english", lowercase=True)
X = pd.DataFrame(vectorizer.fit_transform(df["text"]).toarray())
y = df["type"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

clf = RandomForestClassifier(n_jobs=-1)
clf.fit(X_train, y_train)

"""## 4.1. Testing and Predicting Dataset

The output is classified into Ham (likely non-Spam messages in a string datatype


"""

y_pred = clf.predict(X_test)
y_pred

# 5. Evaluating the Performnce and visuslization

"""## 5. Performance Classification, Prediction and Visualization

This evaluates:
1. The accuracy score (y_test, y_pred), calculating the correct prediction, where output is 0.9712 or 97.12%

2. The confusion matrix (y_test, y_pred), which creates a table showing the true against the predicted labels i.e the counts of correct against the incorrect classifications).
3. sns.headmap which visualizes the confusion matrix with annotated counts as true

4. plt.show(), which displays the heatmap plot

"""

score = accuracy_score(y_test, y_pred)
print("Score: ", score)
cm = confusion_matrix(y_test, y_pred)
sns.heatmap(cm, annot=True, fmt="d")
plt.show()

import pandas as pd
import numpy as np
import re
import string
import matplotlib.pyplot as plt

# Count Spam and Ham messages
class_counts = df['type'].value_counts()

# If labels were converted to numbers
class_counts.index = ['Ham', 'Spam']

# Create bar chart
plt.figure(figsize=(6,4))
plt.bar(class_counts.index, class_counts.values)

plt.title('Distribution of SMS Messages')
plt.xlabel('Message Type')
plt.ylabel('Count')

for i, v in enumerate(class_counts.values):
    plt.text(i, v + 20, str(v), ha='center')

plt.show()

df.loc[:,'type']=df.type.map({'ham':0, 'spam':1})
df['type'] = df['type'].astype(int)
df.head()

"""## TRIANING THE MACHINE LEARNING MODEL

###Neural Network
"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# from sklearn.neural_network import MLPClassifier
# 
# mlp_classifier_model = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=1000)
# mlp_classifier_model.fit(X_train, y_train)
# 
# prediction = mlp_classifier_model.predict(X_test)
# 
# # Calculate and print classification metrics
# print("MLP Classifier")
# print("Accuracy score: {:.2f}".format(accuracy_score(y_test, prediction)))
# print("Precision score: {:.2f}".format(precision_score(y_test, prediction, pos_label='spam')))
# print("Recall score: {:.2f}".format(recall_score(y_test, prediction, pos_label='spam')))
# print("F1 score: {:.2f}".format(f1_score(y_test, prediction, pos_label='spam')))

"""###Multinomial Naive Bayes"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# # Multinomial Naive Bayes model
# from sklearn.naive_bayes import MultinomialNB
# 
# multinomial_nb_model = MultinomialNB()
# multinomial_nb_model.fit(X_train, y_train)  # Train the model
# 
# prediction = multinomial_nb_model.predict(X_test)
# 
# print("Multinomial NB")
# print("Accuracy score: {}".format(accuracy_score(y_test, prediction)))
# print("Precision score: {}".format(precision_score(y_test, prediction, pos_label='spam')))
# print("Recall score: {}".format(recall_score(y_test, prediction, pos_label='spam')))
# print("F1 score: {}".format(f1_score(y_test, prediction, pos_label='spam')))

"""###Bernoulli Naive Bayes"""

# Commented out IPython magic to ensure Python compatibility.
# %%time
# # Bernoulli Naive Bayes model
# from sklearn.naive_bayes import BernoulliNB
# from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
# 
# bernoulli_nb_model = BernoulliNB()
# bernoulli_nb_model.fit(X_train, y_train)
# 
# prediction = bernoulli_nb_model.predict(X_test)
# 
# #Evaluation
# print("Bernoulli NB")
# print("Accuracy score: {}".format(accuracy_score(y_test, prediction)) )
# print("Precision score: {}".format(precision_score(y_test, prediction, pos_label='spam')) )
# print("Recall score: {}".format(recall_score(y_test, prediction, pos_label='spam')))
# print("F1 score: {}".format(f1_score(y_test, prediction, pos_label='spam')))

"""###CONFUSION METRICS"""

from sklearn.metrics import confusion_matrix
models = [("Multinomial NB", multinomial_nb_model), ("Bernoulli NB", bernoulli_nb_model),("MLP Classifier", mlp_classifier_model) ]

fig, axes = plt.subplots(1, 3, figsize=(10, 3))
for i, (model_name, model) in enumerate(models):
    prediction = model.predict(X_test)
    cm = confusion_matrix(y_test, prediction)
    sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", cbar=False, ax=axes[i])
    axes[i].set_title(f"{model_name} - Confusion Matrix")
    axes[i].set_xlabel("Predicted")
    axes[i].set_ylabel("Actual")
plt.tight_layout()
plt.show()

"""###Metric Comparison Heatmap"""

metric_data = []
for model_name, model in models:
    prediction = model.predict(X_test)
    accuracy = accuracy_score(y_test, prediction)
    precision = precision_score(y_test, prediction, pos_label='spam')
    recall = recall_score(y_test, prediction, pos_label='spam')
    f1 = f1_score(y_test, prediction, pos_label='spam')
    metric_data.append([accuracy, precision, recall, f1])
metric_labels = ["Accuracy", "Precision", "Recall", "F1 Score"]
#heatmap for metric comparison
plt.figure(figsize=(6, 3))
sns.heatmap(metric_data, annot=True, fmt=".2f", cbar=False, cmap="summer_r", xticklabels=metric_labels, yticklabels=[model_name for model_name, _ in models])
plt.title("Metric Comparison")
plt.yticks(rotation=0)
plt.xlabel("Metrics")
plt.ylabel("Models")
plt.tight_layout()
plt.show()

import joblib

joblib.dump(model, "spam_email_classifier_model.pkl")
joblib.dump(multinomial_nb_model, 'multinomial_nb_model.pkl')
joblib.dump(bernoulli_nb_model, 'bernoulli_nb_model.pkl')
joblib.dump(mlp_classifier_model, 'mlp_classifier_model.pkl')
joblib.dump(vectorizer, 'vectorizer.pkl')